spring.application.name=Bareum

spring.datasource.url=jdbc:mysql://localhost:3306/bareum?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=bareum1234!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.user.name=admin
spring.security.user.password=1234

google.cloud.vision.credentials.path=C:/keys/second-sandbox-497602-n8-d09f59e9d131.json