spring.application.name=Bareum

spring.datasource.url=jdbc:h2:mem:Bareum
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=js
spring.datasource.password=1234

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.user.name=admin
spring.security.user.password=1234

google.cloud.vision.credentials.path=C:/keys/second-sandbox-497602-n8-d09f59e9d131.json